name: Frontend CI
on:
  push:
    branches: [master, frontendTest]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './front'  # Spécifie le dossier du projet
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'  # Chemin relatif vers le lockfile

      - name: Install dependencies
        working-directory: './front'
        run: npm ci  # Utilise npm clean-install

      - name: Run unit tests
        working-directory: './front'
        run: npm test

      - name: Run integration tests
        working-directory: './front'
        continue-on-error: true
        run: |
          if [ -f "cypress.config.js" ]; then
            npx cypress run --component || echo "::warning::Some integration tests failed"
          else
            echo "No Cypress config found - skipping integration tests"
          fi

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      - name: Install and build
        working-directory: './front'
        run: |
          npm ci
          npm run build
