name: Frontend CI - Tests Automatisés
on:
  push:
    branches: [master, frontendTest]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './front'  # Spécifiez le sous-dossier où se trouve package.json
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests unitaires
        run: npm test || echo "Certains tests ont échoué (mode warning seulement)" && exit 0

      - name: Exécuter les tests d'intégration
        run: npm run test:integration

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './front'  # Même spécification ici
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
