name: Full CI/CD Pipeline

on:
  push:
    branches: [master, frontendTest]
  pull_request:
    branches: [master]

jobs:
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './front'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Verify coverage report
        run: |
          if [ ! -f coverage/lcov.info ]; then
            echo "::error::Coverage file not found!"
            exit 1
          fi
          echo "Coverage report generated successfully"

      - name: Upload coverage for SonarCloud
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage/lcov.info
          retention-days: 1

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: './back'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov

      - name: Run tests with coverage
        working-directory: './back'
        run: |
          PYTHONPATH=$PWD pytest --cov=./ --cov-report xml:coverage.xml

      - name: Verify coverage report
        working-directory: './back'
        run: |
          if [ ! -f coverage.xml ]; then
            echo "::error::Coverage file not found!"
            exit 1
          fi
          echo "Coverage report generated successfully"

      - name: Upload coverage for SonarCloud
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/coverage.xml
          retention-days: 1

  build:
    needs: [frontend-test, backend-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install and build frontend
        working-directory: './front'
        run: |
          npm ci
          npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: front/dist/
          retention-days: 1

  sonarcloud:
    name: SonarCloud Analysis
    needs: [frontend-test, backend-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Verify downloaded artifacts
        run: |
          ls -la artifacts/
          cp artifacts/frontend-coverage/lcov.info front/coverage/
          cp artifacts/backend-coverage/coverage.xml back/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=chaimaeBky_TO-DO_PFA
            -Dsonar.organization=chaimaebky
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=front/coverage/lcov.info
            -Dsonar.python.coverage.reportPaths=back/coverage.xml
            -Dsonar.qualitygate.wait=true
            -Dsonar.sources=front/src,back/
            -Dsonar.tests=front/tests,back/tests
            -Dsonar.test.inclusions=**/*.test.{js,ts},**/*_test.py
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/__pycache__/**
            -Dsonar.cpd.exclusions=**/test/**,**/mocks/**
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.scm.provider=git
            -Dsonar.projectVersion=1.0.${{ github.run_number }}
            -Dsonar.verbose=true

  deploy:
    needs: [build, sonarcloud]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/frontendTest'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build

      - name: Determine environment
        id: env
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            echo "ENV=production" >> $GITHUB_ENV
            echo "Deploying to production"
          elif [ "$GITHUB_REF" == "refs/heads/frontendTest" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "Deploying to staging"
          fi

      - name: Deploy
        run: |
          if [ "$ENV" == "production" ]; then
            echo "Production deployment would happen here"
            # vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          elif [ "$ENV" == "staging" ]; then
            echo "Staging deployment would happen here"
            # vercel --token ${{ secrets.VERCEL_TOKEN }}
          fi
